import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";

const Inter = localfont({
  src: "./fonts/InterVF.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600",
});

const spacegrotesk = localfont({
  src: "./fonts/SpaceGroteskVF.ttf",
  variable: "--font-space-grotesk",
  weight: " 300 400 500 600 700",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Inter.className} ${spacegrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
